apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
        - name: shared-pongs
          persistentVolumeClaim:
            claimName: pongs-claim 
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:745cdec5c459a7ced3eb64e6886af77006ead75f
          volumeMounts:
          - name: shared-logs          
            mountPath: /app/files
          - name: shared-pongs
            mountPath: /app/files
        - name: main-app-generator
          image: outisa/main-application-generator:745cdec5c459a7ced3eb64e6886af77006ead75f
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files

