apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:64ede4837108d4e1360fac724bcef2cab4d04d54
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
        - name: main-app-generator
          image: outisa/main-application-generator:64ede4837108d4e1360fac724bcef2cab4d04d54
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
