apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
        - name: shared-pongs
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:800dd5d0a23a5836a5c6ab185dd348f0da9cef24
          volumeMounts:
          - name: shared-logs          
            mountPath: /app/files
          - name: shared-pongs
            mountPath: /app/pongs
        - name: main-app-generator
          image: outisa/main-application-generator:800dd5d0a23a5836a5c6ab185dd348f0da9cef24
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files

