apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:a898a99738b09156193c0e44e949fe132ff35fb2
          volumeMounts:
          - name: shared-logs          
            mountPath: /app/files
        - name: main-app-generator
          image: outisa/main-application-generator:a898a99738b09156193c0e44e949fe132ff35fb2
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files

