apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:bcd8864a24cdde75bad02e534dfe733a8e3abe11
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3003
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hashgenerator-cm
                  key: MESSAGE
          volumeMounts:
          - name: shared-logs          
            mountPath: /app/files
        - name: main-app-generator
          image: outisa/main-application-generator:56e87c3249ce2dc2c04311d3d9cac423c38886a4
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files

