apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:f57bdf1d93c0f6bfd089c285192f61175ca0ea41
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
        - name: main-app-generator
          image: outisa/main-application-generator:f57bdf1d93c0f6bfd089c285192f61175ca0ea41
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
