apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:068061c4dde91efc34822f0d759c3a1ff4e161f9
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
        - name: main-app-generator
          image: outisa/main-application-generator:068061c4dde91efc34822f0d759c3a1ff4e161f9
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
