apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:cc94b325fd1bbba8d847cdb2901822643d749af9
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hashgenerator-cm
                  key: MESSAGE
          volumeMounts:
          - name: shared-logs          
            mountPath: /app/files
        - name: main-app-generator
          image: outisa/main-application-generator:cc94b325fd1bbba8d847cdb2901822643d749af9
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files

