apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-string
          emptyDir: {}
      containers:
        - name: main-app-finder
          image: outisa/main-application-finder:53533d5c8777e70f3ec4858b05e5f788f2118b8b
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
        - name: main-app-generator
          image: outisa/main-application-generator:53533d5c8777e70f3ec4858b05e5f788f2118b8b
          volumeMounts:
            - mountPath: /app/files
              name: shared-logs
